---
title: "add_gene_id_to_antismash.Rmd"
author: "Kate Lee"
date: "01/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


Read in data from gene set and from antismash summarised results
```{r get_data}
# summarised antismash results
as_eel <- read.delim("results/Eel_masked_antismash_sum.txt", header = TRUE, sep = "\t")
as_fes <- read.delim("results/E.festucae_E2368_antismash_sum.txt", header = TRUE, sep = "\t")
as_typ <- read.delim("results/E.typhina_E8_antismash_sum.txt", header = TRUE, sep = "\t")
as_pol_eel <- read.delim("results/E.elymi_728_ONP_polished_antismash_sum.txt", header = TRUE, sep = "\t")
  
# gene set data from David Winters
gs_eel <- read.delim("../gene_sets/Epichloe_elymi_NfE728.gff3", header = FALSE, sep = "\t", comment.char = "#")
gs_fes <- read.delim("../gene_sets/Epichloe_festucae_E2368.gff3", header = FALSE, sep = "\t", comment.char = "#")
gs_typ <- read.delim("../gene_sets/Epichloe_typhina_E8.gff3", header = FALSE, sep = "\t", comment.char = "#")

head(gs_eel)
gs_eel[(gs_eel$V1 == "Eel_0005"),]
```

```{r annotate_antismash_with_gene_id_from_gff3}

head(as_eel)


gs_eel[(gs_eel$V1 == "Eel_0005") && (gs_eel$V4 == 9890) && (gs_eel$V5 == 12253), "V9"]
as_eel <- mutate(gene_id = gs_eel[(gs_eel$V1 == as_eel$Chr) && (gs_eel$V4 == as_eel$gene_start) && (gs_eel$V5 == as_eel$gene_end), "V9"])

```