---
title: "UpsetR_test"
author: "Kate"
date: "3 May 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

from vignette
https://cran.r-project.org/web/packages/UpSetR/vignettes/set.metadata.plots.html

```{r  get_data}
library(UpSetR)
movies <- read.csv(system.file("extdata", "movies.csv", package = "UpSetR"), 
    header = T, sep = ";")

head(movies)
colnames(movies)
```

```{r set_metadata}

sets <- names(movies[3:19])    # grab the colnames of movie types
avgRottenTomatoesScore <- round(runif(17, min = 0, max = 90))   # generate a random rotten tomato score for each movie type 
metadata <- as.data.frame(cbind(sets, avgRottenTomatoesScore))    # set up metadata data frame
names(metadata) <- c("sets", "avgRottenTomatoesScore")
metadata$avgRottenTomatoesScore <- as.numeric(as.character(metadata$avgRottenTomatoesScore)) # ensure average score is numeric after cbind function
sets
```


```{r basic_upsetRplot}
upset(movies,                                                                                   # dataset
      set.metadata = list(data = metadata,                                                      # assign metadata
      plots = list(list(type = "hist", column = "avgRottenTomatoesScore", assign = 20))))       # extra plot 

```


```{r add_heatmap}
# add city where a genre is most popular

Cities <- sample(c("Boston", "NYC", "LA"), 17, replace = T)
metadata <- cbind(metadata, Cities)
metadata$Cities <- as.character(metadata$Cities)
metadata[which(metadata$sets %in% c("Drama", "Comedy", "Action", "Thriller", 
    "Romance")), ]


upset(movies, 
      set.metadata = list(data = metadata, 
                          plots = list(list(type = "heat", column = "Cities", assign = 10, colors = c(Boston = "green", NYC = "navy", LA = "purple")))))
```


```{r add_boolean_or_heatmap}
# add in where genres are accepted well overseas

accepted <- round(runif(17, min = 0, max = 1))
metadata <- cbind(metadata, accepted)
metadata[which(metadata$sets %in% c("Drama", "Comedy", "Action", "Thriller", 
    "Romance")), ]


# boolean returns color
upset(movies, 
      set.metadata = list(data = metadata, 
                          plots = list(list(type = "bool", column = "accepted", assign = 5, colors = c("#FF3333", "#006400")))))

# heatmap
upset(movies, 
      set.metadata = list(data = metadata, 
                          plots = list(list(type = "heat", column = "accepted", assign = 5, colors = c("red", "green")))))
```


```{r set_text}
upset(movies, set.metadata = list(data = metadata, plots = list(list(type = "text", 
    column = "Cities", assign = 10, colors = c(Boston = "green", NYC = "navy", 
        LA = "purple")))))

```

```{r apply_metadata_to_matrix}
upset(movies, 
      set.metadata = list(data = metadata, 
                          plots = list(list(type = "hist", column = "avgRottenTomatoesScore", assign = 20), 
                                       list(type = "matrix_rows", column = "Cities", colors = c(Boston = "green", NYC = "navy", LA = "purple"), alpha = 0.5))))
```